package com.example.ui.tools.pdf

import android.content.Context
import android.content.Intent
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.graphics.Color as AndroidColor
import android.graphics.Paint
import android.graphics.pdf.PdfDocument
import android.net.Uri
import android.widget.Toast
import androidx.activity.compose.BackHandler
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.PickVisualMediaRequest
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.AddPhotoAlternate
import androidx.compose.material.icons.filled.ContentCopy
import androidx.compose.material.icons.filled.Download
import androidx.compose.material.icons.filled.PictureAsPdf
import androidx.compose.material.icons.filled.Share
import androidx.compose.material3.Button
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.FilterChip
import androidx.compose.material3.HorizontalDivider
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.material3.TopAppBar
import androidx.compose.material3.TopAppBarDefaults
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableIntStateOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.core.content.FileProvider
import com.example.ads.TopBannerAd
import com.example.util.ImageExportUtils
import java.io.File
import java.io.FileOutputStream

// ==========================================
// 1. TEXT TO PDF & IMAGE TO PDF
// ==========================================

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun TextToPdfScreen(onBack: () -> Unit) {
    BackHandler { onBack() }
    val context = LocalContext.current

    var docTitle by remember { mutableStateOf("Project Specification Document") }
    var docAuthor by remember { mutableStateOf("OmniTools Author") }
    var docContent by remember {
        mutableStateOf(
            "This document was created directly using OmniTools.\n\n" +
            "Key Features:\n" +
            "• Clean PDF formatting and pagination\n" +
            "• Standard A4 document canvas (595 x 842 points)\n" +
            "• Instant PDF export and WhatsApp/Email sharing\n\n" +
            "Thank you for choosing OmniTools All-in-One Utility Kit!"
        )
    }

    fun generateAndSharePdf(title: String, author: String, content: String, isShare: Boolean) {
        try {
            val pdfDoc = PdfDocument()
            val pageInfo = PdfDocument.PageInfo.Builder(595, 842, 1).create() // A4 size
            val page = pdfDoc.startPage(pageInfo)
            val canvas = page.canvas

            val paint = Paint().apply {
                isAntiAlias = true
                color = AndroidColor.BLACK
            }

            // Title
            paint.textSize = 24f
            paint.isFakeBoldText = true
            canvas.drawText(title, 40f, 60f, paint)

            // Author & Date
            paint.textSize = 12f
            paint.isFakeBoldText = false
            paint.color = AndroidColor.DKGRAY
            canvas.drawText("Author: $author  |  Generated by OmniTools", 40f, 85f, paint)

            paint.color = AndroidColor.LTGRAY
            paint.strokeWidth = 1f
            canvas.drawLine(40f, 100f, 555f, 100f, paint)

            // Body text
            paint.color = AndroidColor.BLACK
            paint.textSize = 13f
            var currentY = 130f
            val lines = content.split("\n")
            for (line in lines) {
                if (currentY > 800f) break
                canvas.drawText(line, 40f, currentY, paint)
                currentY += 20f
            }

            pdfDoc.finishPage(page)

            val file = File(context.cacheDir, "OmniTools_Doc_${System.currentTimeMillis()}.pdf")
            val outputStream = FileOutputStream(file)
            pdfDoc.writeTo(outputStream)
            pdfDoc.close()
            outputStream.close()

            val uri: Uri = FileProvider.getUriForFile(context, "${context.packageName}.provider", file)
            if (isShare) {
                val shareIntent = Intent(Intent.ACTION_SEND).apply {
                    type = "application/pdf"
                    putExtra(Intent.EXTRA_STREAM, uri)
                    putExtra(Intent.EXTRA_SUBJECT, title)
                    addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
                }
                context.startActivity(Intent.createChooser(shareIntent, "Share PDF"))
            } else {
                Toast.makeText(context, "PDF saved to app documents cache!", Toast.LENGTH_SHORT).show()
            }
        } catch (e: Exception) {
            Toast.makeText(context, "Error generating PDF: ${e.message}", Toast.LENGTH_SHORT).show()
        }
    }

    Scaffold(
        topBar = {
            Column {
                TopBannerAd()
                TopAppBar(
                    title = { Text("Text → PDF Maker") },
                    navigationIcon = {
                        IconButton(onClick = onBack) {
                            Icon(Icons.AutoMirrored.Filled.ArrowBack, contentDescription = "Back")
                        }
                    },
                    colors = TopAppBarDefaults.topAppBarColors(containerColor = MaterialTheme.colorScheme.surface)
                )
            }
        }
    ) { padding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(padding)
                .verticalScroll(rememberScrollState())
                .padding(16.dp),
            verticalArrangement = Arrangement.spacedBy(16.dp)
        ) {
            OutlinedTextField(value = docTitle, onValueChange = { docTitle = it }, label = { Text("Document Title") }, modifier = Modifier.fillMaxWidth())
            OutlinedTextField(value = docAuthor, onValueChange = { docAuthor = it }, label = { Text("Author Name") }, modifier = Modifier.fillMaxWidth())
            OutlinedTextField(
                value = docContent,
                onValueChange = { docContent = it },
                label = { Text("Document Content / Paragraphs") },
                modifier = Modifier.fillMaxWidth(),
                minLines = 8
            )

            Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(12.dp)) {
                Button(
                    onClick = { generateAndSharePdf(docTitle, docAuthor, docContent, isShare = false) },
                    modifier = Modifier.weight(1f)
                ) {
                    Icon(Icons.Filled.PictureAsPdf, contentDescription = null, modifier = Modifier.size(18.dp))
                    Spacer(Modifier.width(6.dp))
                    Text("Export PDF")
                }
                OutlinedButton(
                    onClick = { generateAndSharePdf(docTitle, docAuthor, docContent, isShare = true) },
                    modifier = Modifier.weight(1f)
                ) {
                    Icon(Icons.Filled.Share, contentDescription = null, modifier = Modifier.size(18.dp))
                    Spacer(Modifier.width(6.dp))
                    Text("Share PDF")
                }
            }
        }
    }
}

// ==========================================
// 2. WORD & CHARACTER COUNTER
// ==========================================

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun WordAndCharacterCounterScreen(onBack: () -> Unit) {
    BackHandler { onBack() }
    val context = LocalContext.current

    var textInput by remember { mutableStateOf("The quick brown fox jumps over the lazy dog. OmniTools makes productivity simple and fast!") }

    val charCount = textInput.length
    val charNoSpaces = textInput.replace(" ", "").replace("\n", "").length
    val words = textInput.trim().split("\\s+".toRegex()).filter { it.isNotBlank() }
    val wordCount = words.size
    val sentenceCount = textInput.split("[.!?]+".toRegex()).filter { it.isNotBlank() }.size
    val paragraphCount = textInput.split("\n\n").filter { it.isNotBlank() }.size

    // Average reading speed = 200 words per minute, Speaking = 130 wpm
    val readingTimeSec = (wordCount * 60) / 200
    val speakingTimeSec = (wordCount * 60) / 130

    Scaffold(
        topBar = {
            Column {
                TopBannerAd()
                TopAppBar(
                    title = { Text("Word & Character Counter") },
                    navigationIcon = {
                        IconButton(onClick = onBack) {
                            Icon(Icons.AutoMirrored.Filled.ArrowBack, contentDescription = "Back")
                        }
                    },
                    colors = TopAppBarDefaults.topAppBarColors(containerColor = MaterialTheme.colorScheme.surface)
                )
            }
        }
    ) { padding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(padding)
                .verticalScroll(rememberScrollState())
                .padding(16.dp),
            verticalArrangement = Arrangement.spacedBy(16.dp)
        ) {
            // Live Stats Grid
            Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                Card(
                    modifier = Modifier.weight(1f),
                    colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.primaryContainer)
                ) {
                    Column(modifier = Modifier.padding(14.dp), horizontalAlignment = Alignment.CenterHorizontally) {
                        Text("Words", fontSize = 11.sp)
                        Text("$wordCount", fontSize = 24.sp, fontWeight = FontWeight.Bold, color = MaterialTheme.colorScheme.primary)
                    }
                }
                Card(
                    modifier = Modifier.weight(1f),
                    colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.secondaryContainer)
                ) {
                    Column(modifier = Modifier.padding(14.dp), horizontalAlignment = Alignment.CenterHorizontally) {
                        Text("Characters", fontSize = 11.sp)
                        Text("$charCount", fontSize = 24.sp, fontWeight = FontWeight.Bold, color = MaterialTheme.colorScheme.secondary)
                    }
                }
            }

            OutlinedTextField(
                value = textInput,
                onValueChange = { textInput = it },
                label = { Text("Type or paste text here") },
                modifier = Modifier.fillMaxWidth(),
                minLines = 6
            )

            // Detailed Stats Card
            Card(
                modifier = Modifier.fillMaxWidth(),
                colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceVariant)
            ) {
                Column(modifier = Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(10.dp)) {
                    Text("Detailed Text Analytics", fontWeight = FontWeight.Bold)
                    HorizontalDivider()
                    Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
                        Text("Characters (no spaces):")
                        Text("$charNoSpaces", fontWeight = FontWeight.SemiBold)
                    }
                    Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
                        Text("Sentences:")
                        Text("$sentenceCount", fontWeight = FontWeight.SemiBold)
                    }
                    Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
                        Text("Paragraphs:")
                        Text("$paragraphCount", fontWeight = FontWeight.SemiBold)
                    }
                    Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
                        Text("Estimated Reading Time:")
                        Text("${readingTimeSec}s", fontWeight = FontWeight.SemiBold)
                    }
                    Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
                        Text("Estimated Speaking Time:")
                        Text("${speakingTimeSec}s", fontWeight = FontWeight.SemiBold)
                    }
                }
            }

            // Platform Limits Card
            Card(
                modifier = Modifier.fillMaxWidth(),
                colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.5f))
            ) {
                Column(modifier = Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) {
                    Text("Social & SEO Limits", fontWeight = FontWeight.Bold)
                    Text("• Twitter / X Post: $charCount / 280 ${if (charCount > 280) "❌ Exceeded" else "✅ OK"}")
                    Text("• SMS Text Message: $charCount / 160 ${if (charCount > 160) "❌ (2+ segments)" else "✅ 1 segment"}")
                    Text("• Google SEO Meta Title: $charCount / 60 ${if (charCount > 60) "⚠️ Truncated" else "✅ Optimal"}")
                }
            }
        }
    }
}

// ==========================================
// 3. CASE CONVERTER SCREEN
// ==========================================

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun CaseConverterScreen(onBack: () -> Unit) {
    BackHandler { onBack() }
    val context = LocalContext.current

    var inputText by remember { mutableStateOf("hello world from omnitools") }

    val conversions = listOf(
        "UPPERCASE" to inputText.uppercase(),
        "lowercase" to inputText.lowercase(),
        "Title Case" to inputText.split(" ").joinToString(" ") { it.replaceFirstChar { c -> c.uppercase() } },
        "Sentence case" to inputText.lowercase().replaceFirstChar { it.uppercase() },
        "camelCase" to inputText.split(" ").mapIndexed { idx, s -> if (idx == 0) s.lowercase() else s.lowercase().replaceFirstChar { it.uppercase() } }.joinToString(""),
        "snake_case" to inputText.lowercase().replace(" ", "_"),
        "kebab-case" to inputText.lowercase().replace(" ", "-"),
        "Alternating cAsE" to inputText.mapIndexed { i, c -> if (i % 2 == 0) c.lowercaseChar() else c.uppercaseChar() }.joinToString("")
    )

    Scaffold(
        topBar = {
            Column {
                TopBannerAd()
                TopAppBar(
                    title = { Text("Case Converter") },
                    navigationIcon = {
                        IconButton(onClick = onBack) {
                            Icon(Icons.AutoMirrored.Filled.ArrowBack, contentDescription = "Back")
                        }
                    },
                    colors = TopAppBarDefaults.topAppBarColors(containerColor = MaterialTheme.colorScheme.surface)
                )
            }
        }
    ) { padding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(padding)
                .verticalScroll(rememberScrollState())
                .padding(16.dp),
            verticalArrangement = Arrangement.spacedBy(16.dp)
        ) {
            OutlinedTextField(
                value = inputText,
                onValueChange = { inputText = it },
                label = { Text("Input Text to Convert") },
                modifier = Modifier.fillMaxWidth()
            )

            conversions.forEach { (type, converted) ->
                Card(
                    modifier = Modifier.fillMaxWidth(),
                    colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.5f))
                ) {
                    Row(
                        modifier = Modifier
                            .fillMaxWidth()
                            .padding(12.dp),
                        horizontalArrangement = Arrangement.SpaceBetween,
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        Column(modifier = Modifier.weight(1f)) {
                            Text(type, fontSize = 11.sp, fontWeight = FontWeight.Bold, color = MaterialTheme.colorScheme.primary)
                            Text(converted, fontSize = 14.sp, fontWeight = FontWeight.Medium)
                        }
                        IconButton(
                            onClick = { ImageExportUtils.copyToClipboard(context, converted, type) }
                        ) {
                            Icon(Icons.Filled.ContentCopy, contentDescription = "Copy", modifier = Modifier.size(18.dp))
                        }
                    }
                }
            }
        }
    }
}
